### ISSUE TITLE
OS package metadata file name is in base64 encoded format 

### ISSUE THREAD

**Issue by bsalunke** [GoogleContainerTools/distroless#581] opened 2020-09-13 08:03 UTC
How to reproduce the issue:

Clone the repo
`git clone https://github.com/GoogleContainerTools/distroless.git`

run build command
`bazel build //package_manager:dpkg_parser.par`

Build a container image
`bazel run //java:java11_debian10`

The docker image build after above step is:
`bazel/java                 java11_debian10     26e61d7dd5a1        50 years ago        200MB`

When I saved this image as tar and extracted the image file system from tar file. 
In the base layer file system I found the OS package file names are in base65 encoded format. 

`docker save 26e61d7dd5a1 -o 26e61d7dd5a1.tar`

`tar -xvf 26e61d7dd5a1.tar`

In base layer file system, the OS package file name is base64 encoded, 
```
$/home/ubuntu/distroless/tar/3d3cdffab48560cb670466c3d6203c0d86c503dfdd896fce76e08f1dec7971d4/var/lib/dpkg/status.d
$ ls
bmV0YmFzZQ==  dHpkYXRh  YmFzZS1maWxlcw==
```
Is it expected? Is there anything changed recently?

**Comment by chanseokoh** [comment] 2020-09-16 14:38
I can reproduce the issue locally.

```
$ bazel run //java:java11_debug_debian10
$ docker run --rm --entrypoint /busybox/ls bazel/java:java11_debug_debian10 var/lib/dpkg/status.d
YmFzZS1maWxlcw==
Zm9udGNvbmZpZy1jb25maWc=
Zm9udHMtZGVqYXZ1LWNvcmU=
b3Blbmpkay0xMS1qZGstaGVhZGxlc3M=
b3Blbmpkay0xMS1qcmUtaGVhZGxlc3M=
b3BlbnNzbA==
bGliYzY=
bGliZ29tcDE=
bGliZ2NjMQ==
bGliZXhwYXQx
bGliZm9udGNvbmZpZzE=
bGliZnJlZXR5cGU2
bGlianBlZzYyLXR1cmJv
bGlibGNtczItMg==
bGlic3NsMS4x
bGlic3RkYysrNg==
bGlicG5nMTYtMTY=
bGlidXVpZDE=
bmV0YmFzZQ==
dHpkYXRh
emxpYjFn
```

However, at least the published images don't have the issue. The reason is unclear, but our build pipeline on GCB gets this correct.
```
$ docker pull gcr.io/distroless/java-debian10:11-debug
11-debug: Pulling from distroless/java-debian10
Digest: sha256:2459fcc57a972548be0a19017af375640962f6a2b6acdb304960f86d99ceb7cf
Status: Image is up to date for gcr.io/distroless/java-debian10:11-debug
gcr.io/distroless/java-debian10:11-debug
$ docker run --rm --entrypoint /busybox/ls gcr.io/distroless/java-debian10:11-debug var/lib/dpkg/status.d
base
fontconfig
fonts
libc6
libexpat1
libfontconfig1
libfreetype6
libgcc1
libgomp1
libjpeg62
liblcms2
libpng16
libssl1
libstdc
libuuid1
netbase
openjdk
openssl
tzdata
zlib1g
```

Anyways, [`rules_docker`](https://github.com/bazelbuild/rules_docker) that Distroless depends on is the one creating the files. See the following issues.

https://github.com/bazelbuild/rules_docker/pull/239
https://github.com/bazelbuild/rules_docker/issues/182

Please file a bug against `rules_docker`. (I appreciate your update here after you file an issue.)

Closing, as this is an issue in `rules_docker` and the released images are unaffected.

**Closed by chanseokoh** 2020-09-16 14:38 UTC
