### ISSUE TITLE
Switch to run as non-root?

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/distroless#339] opened 2019-03-25 22:10 UTC
Up for discussions on https://github.com/GoogleContainerTools/distroless/issues/306#issuecomment-476393415, as this will be a fairly radical breaking change and I think we need opinions from many people. That is, put User metadata to the distroless base so that by default any command runs as non-root.

If we do this, not sure if `nobody` would be a good fit, considering its nature. (Also `nobody`'s home would be set to `/nonexistent`), so we may need to add a proper new user?

**Comment by briandealwis** [comment] 2019-03-27 16:16
Duplicate of #235

**Closed** 2019-03-27 16:17 UTC
