### ISSUE TITLE
is distroless support mutil-arch image?

### ISSUE THREAD

**Issue by jinchihe** [GoogleContainerTools/distroless#406] opened 2019-09-20 02:40 UTC
/question

Hello, I just wonder that if distroless support mutil-arch image? Docker and Google Cloud build support mutil-arch image.  Thanks a lot!
https://medium.com/@bamnet/building-multiarch-docker-images-8a70002b3476

**Comment by nlopezgi** [comment] 2019-09-25 17:59
see https://github.com/bazelbuild/rules_docker/issues/300 which discusses adding support for multi-arch images to rules_docker. Doing that precludes adding support for this for distroless, afaik, as distroless is built with rules_docker. Please comment there about your use case for this so we can collect more evidence of why this is needed.

**Comment by outofcoffee** [comment] 2019-12-21 21:42
Because of the above distroless appears to be amd64 only. Output of current manifest:

```bash
$ manifest-tool inspect gcr.io/distroless/base-debian10:nonroot
gcr.io/distroless/base-debian10:nonroot: manifest type: application/vnd.docker.distribution.manifest.v2+json
      Digest: sha256:afb0261acca92ecd6a19ab4e32aa05a55bd096faa26afdb0c24e2a359f91386d
Architecture: amd64
          OS: linux
    # Layers: 3
      layer 1: digest = sha256:cfb92865f5ba0896315e32338a1e96810f87b19ba7703a4a3c4a5b224b6c7e5f
      layer 2: digest = sha256:8dd350b5e0d523fff026145128f80cfa4148e83a33226eae2ee679aeda36dc0b
      layer 3: digest = sha256:3c2cba919283a210665e480bcbf943eaaf4ed87a83f02e81bb286b8bdead0e75
```

Sadly this means a bunch of downstream dependents ([for example](https://github.com/GoogleCloudPlatform/cloudsql-proxy)), are also amd64 architecture only, making [use on ARM infeasible](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/199) for those projects without [recompiling](https://github.com/outofcoffee/arm32v7-cloudsql-proxy).

**Comment by chanseokoh** [comment] 2020-08-18 18:12
X-ref: #346 #569

To avoid fragmentation, I'm closing this as a duplicate of #346. Please migrate discussions if you want.

**Closed by chanseokoh** 2020-08-18 18:12 UTC
Labels: kind/question
