### ISSUE TITLE
Java 11.0.8

### ISSUE THREAD

**Issue by NikolayMetchev** [GoogleContainerTools/distroless#555] opened 2020-07-27 09:37 UTC
Hello,
At the moment the latest java 11 distroless image (https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java@sha256:00b6c5ad8f50f6d4434d9557900ab89a84d349264cc07bd842f1be1e5f2aa827/details?tab=info) seems to be running openJDK 11.0.6. Can we update it to 11.0.8?
Many thanks.

**Comment by chanseokoh** [comment] 2020-07-27 13:55
Closing as a duplicate of https://github.com/GoogleContainerTools/distroless/issues/524#issuecomment-640797408.

TL;DR: use the Debian 10-based `gcr.io/distroless/java-debian10:11`. (We've notified that Debian 10 today updated Java to 11.0.8, so Distroless Debian 10 with Java 11.0.8 will go live by EOD as well.)

**Closed by chanseokoh** 2020-07-27 13:55 UTC
