### ISSUE TITLE
Add support for multi-arch image

### ISSUE THREAD

**Issue by maxiwell** [GoogleContainerTools/distroless#569] opened 2020-08-18 17:52 UTC
I'm working on [kubernetes-csi](https://github.com/kubernetes-csi) and my main focus is on multi-arch enablement to ensure feature parity between them all, specially ppc64le. In order to achieve that we need to add the fat manifest feature as part of distroless/static image. We also need to handle the improvements in the infrastructure that generates those images, to ensure it can be tested and validated.

With that said, how could we start collaborating to achieve that goal? Is there any constrain on making the distroless images multi-arch?

Thank you

**Comment by jonjohnsonjr** [comment] 2020-08-18 18:00
AFAIK, there's nothing really platform specific in distroless/static. It wouldn't be hard to hack something together that can generate a multi-arch version of it (for arbitrary platforms).

The annoying bit is that we'd have to either do that outside of bazel or do some work in [rules_docker](https://github.com/bazelbuild/rules_docker/issues/300) to support this.

**Comment by rpsene** [comment] 2020-08-18 18:09
@jonjohnsonjr for ppc64le we can offer a VM to be added as a Bazel node. You can also consider using Travis-CI, which supports amd64, arm, ppc64le and s390x.

**Comment by chanseokoh** [comment] 2020-08-18 18:10
X-ref: #406 #346

To avoid fragmentation, I'm closing this as a duplicate of #346. Please migrate discussions if you want.

**Comment by chanseokoh** [comment] 2020-08-18 18:11
But according to what @jonjohnsonjr said and https://github.com/GoogleContainerTools/distroless/issues/346#issuecomment-482670577, `distroless/static` may already be agonistic to architecture.

**Closed by chanseokoh** 2020-08-18 18:10 UTC
