### ISSUE TITLE
Docker images: creation time set to the epoch

### ISSUE THREAD

**Issue by JnRouvignac** [GoogleContainerTools/distroless#288] opened 2019-01-31 13:46 UTC
Note that the `base`, `java:8` and `java:11` images are impacted. Possibly others.
Here is the proof:

```
$ docker history gcr.io/distroless/java:11
IMAGE               CREATED             CREATED BY          SIZE                COMMENT
a4338971ab0a        49 years ago        bazel build ...     170MB               
<missing>           49 years ago        bazel build ...     1.93MB              
<missing>           49 years ago        bazel build ...     15.1MB              
<missing>           49 years ago        bazel build ...     1.81MB 
```

```
$ docker inspect gcr.io/distroless/java:8 | head -n 20
[
    {
        "Id": "sha256:9c0bc85b4448a3a3eb940cfd696d832826bf45d5b103e16ad3ea09b6706be9a0",
        "RepoTags": [
            "gcr.io/distroless/java:8"
        ],
        "RepoDigests": [
            "gcr.io/distroless/java@sha256:1ad1b80e9815ba2a5a4e019496ffd6b326a002070c30a09dfa5dca53680f9e2c"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "1970-01-01T00:00:00Z",
        ...
```

**Comment by briandealwis** [comment] 2019-01-31 15:08
Duplicate of #242

**Closed by briandealwis** 2019-01-31 15:08 UTC
