### ISSUE TITLE
libstdc++.so.6: version `CXXABI_1.3.11' not found

### ISSUE THREAD

**Issue by sebastianst** [GoogleContainerTools/distroless#234] opened 2018-08-28 17:47 UTC
I use `gcr.io/distroless/cc` as the second stage in my multi-stage build and when trying to run my compiled app, I get the following error:
```
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found
```
The build image is `gcc:latest`, which is based on `debian:stretch`. Shouldn't the `libstdc++.so.6` versions be compatible? If not, what's the recommended build image to use for C++ sources that need g++ version 8?

**Comment by urbanonymous** [comment] 2019-05-13 17:31
Same issue here

**Comment by chanseokoh** [comment] 2019-05-13 19:31
I cannot know what the versions were for gcc in `gcc:latest` and `libstdc++` in distroless at the time when the issue was created back in Aug 2018, but I *think* `gcc:8` could work, because I see the library in `gcc:8` is same as the one in distroless. If `gcc:8` doesn't work, then as of now, `debian:strech` ships gcc 6.3 (which would match if distroless shipped gcc), so I'd try gcc 6.3 as a last resort.

Alternatively, perhaps you could use the option to switch between different C++ ABIs with `-fabi-version` in newer compilers, but I haven't tried this myself.

**Comment by HunterLarco** [comment] 2019-09-03 19:28
I'm still experiencing this issue :/ any advice on how to work around it?

Using `-fabi-version` is not fixing the issue.

**Comment by donmccasland** [comment] 2019-11-01 17:31
Closing old bug.  Please reopen with steps to reproduce if still valid.

**Closed by donmccasland** 2019-11-01 17:31 UTC
