### ISSUE TITLE
Unable to use 'exec' in 'java:debug' image

### ISSUE THREAD

**Issue by varundhall** [GoogleContainerTools/distroless#365] opened 2019-05-21 10:21 UTC
I've a Java container image which doesn't stop after the program completes. I've tried with `System.exit(0)` and with `Runtime.getRuntime().halt(0)` still no success.

I was trying to debug by looking inside the container, running on Google Kubernetes Engine. But I'm not able to use any bash command. Is this expected behaviour?

Can we have some more docs about using the debug images?

Ref: https://stackoverflow.com/questions/56220637/docker-container-doesnt-exit-after-completing-program

**Comment by briandealwis** [comment] 2019-05-22 15:32
It sounds like you have a non-daemon thread still running?

Distroless images are minimal and do not have shells.  There are [`:debug` variants](https://github.com/GoogleContainerTools/distroless#debug-images) that have `busybox` installed as `/busybox/sh`.  But neither the production nor debug images include JDK diagnostic commands like `jstack` though (#350).

You might be able to ssh to the node and send a SIGQUIT to the JVM process to trigger dumping its stack to the console.

I'm going to close this as it's working as intended, and follow-ups on diagnostics is in #350.

**Closed by briandealwis** 2019-05-22 15:32 UTC

**Comment by mikaelstaldal** [comment] 2019-05-27 08:06
Non-daemon threads running should normally not block `System.exit()`.
