### ISSUE TITLE
Dangling Images getting created

### ISSUE THREAD

**Issue by namachivayam2015** [GoogleContainerTools/distroless#386] opened 2019-07-24 05:43 UTC
I'm trying to convert my existing spring boot app docker image to distroless docker. I was referring to the java sample below,
https://github.com/GoogleContainerTools/distroless/blob/master/examples/java/Dockerfile

I was able to create a image and when started, it works fine as expected.

But i can able to see a dangling image getting created during every docker build. Am i doing anything wrong here or is it a side effect of multi-stage docker execution?

Below is the Dockerfile used to generate the distroless-app image.
**Distroless-Dockerfile**

```
FROM openjdk:8-jre-alpine AS build-env
ADD build/libs/demo-0.0.1-SNAPSHOT.jar /app/demo-app.jar
WORKDIR /app
RUN echo ${JAR_FILE}
RUN apk update && \
 apk add --no-cache openssl ca-certificates wget && \
 apk update ca-certificates && \
 apk del openssl
RUN wget https://github.com/Droplr/aws-env/raw/master/bin/aws-env-linux-amd64 -O /bin/aws-env && \
 chmod +x /bin/aws-env
CMD eval $(aws-env) && java -jar -Dprofile= demo-app.jar

FROM gcr.io/distroless/java:8
COPY --from=build-env /app /app
WORKDIR /app
CMD ["demo-app.jar"]
```

![image](https://user-images.githubusercontent.com/14848958/61767862-2f1bd980-ae03-11e9-9fc7-5e8c1342f5fa.png)

Also i don't see much difference in the image size when compared to image generated by traditional way. Just wanted to confirm whether this is expected behavior.

**Comment by chanseokoh** [comment] 2019-07-24 15:26
I don't know what it means by "dangling" images. Are you referring to the `<none>` line in the screenshot? From my experience, that's working as intended with multi-stage building, since it most likely refers to the unnamed first image built as the first step. If you have three steps, you'll most likely see two lines of `<none>`. You can check this with `docker inspect 7fee9f56594a`, which will show you 

```
[/bin/sh -c eval $(aws-env) && java -jar -Dprofile= demo-app.jar]
```

That said, I think `CMD eval $(aws-env) && java -jar -Dprofile= demo-app.jar` is useless and does not play any role. Probably you want to replace the `CMD` in the last line with it.

In any case, this is irrelevant of Distroless. Use a different FROM image, and you will see the exact same.

Lastly, it may be possible that building the Dockerfile again and again creates more and more `<none>` layers, and if that's happening, you are dealing with [non-reproducible image builds](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#please-tell-me-more-about-reproducibility), which may be a concern to you.

That said, if you are concerned, how about trying [Jib](https://github.com/GoogleContainerTools/jib)? It could as simple as doing

`mvn compile com.google.cloud.tools:jib-maven-plugin:1.4.0:dockerBuild -Dimage=distroless-app`

even without modifying your `pom.xml`, and it will containerize your app using Distroless by default (configurable) and push it to your local Docker. Should work with a Spring Boot app too.

**Comment by chanseokoh** [comment] 2019-07-24 15:28
I think I explained all the things, so I am going to close this. It's also unrelated to Distroless. I also recommend trying Jib.

**Closed by chanseokoh** 2019-07-24 15:28 UTC
