### ISSUE TITLE
Add Java SubstrateVM Base Image

### ISSUE THREAD

**Issue by Jotschi** [GoogleContainerTools/distroless#217] opened 2018-07-11 22:23 UTC
It would be nice to see a base image which could be used to generate distroless docker images which contain an app which was build using [GraalVM SubstrateVM](https://github.com/oracle/graal/tree/master/substratevm). SubstrateVM generates static compiled native executables of Java Programs which do not require an additional JVM environment.

I was able to run such images using the `gcr.io/distroless/base` image by adding the `libz.so.1`. I saw that the java base image is already containing the lib.

Example docker file:

```
FROM gcr.io/distroless/base
ADD vertx-graalvm-native-image-test-0.0.1-SNAPSHOT app
ADD libz.so.1 /lib
CMD ["/app"]
```

I'm not familiar with Bazel but it should be easy to just copy the java build env and remove the JRE from the build.

**Comment by dlorenc** [comment] 2018-07-12 15:23
cc @patflynn

**Comment by lathama** [comment] 2018-07-12 15:25
Using Docker multistage this is easy.

`FROM debian:stable-slim AS build-env

FROM gcr.io/distroless/base
COPY app /app
COPY --from=build-env /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libz.so.1
CMD ["/app"]
`

**Comment by patflynn** [comment] 2018-07-12 15:27
My first thought is that the distroless/base is the right base-image for this kind of executable.  Could we just add libz to it?

**Comment by lathama** [comment] 2018-07-12 15:51
Adding items like libz could open the door for adding more and more. The user and the user's build environment can add items like this when and where needed. The tooling is there.

**Comment by dlorenc** [comment] 2018-07-16 17:06
We could stick this in cc, which is what the java base uses. That would still keep base clean, and provide a slimmer base for java without the JVM.

**Comment by loosebazooka** [comment] 2019-02-11 18:55
@dlorenc this has come up again. Any objections to putting this in the cc image?

**Comment by loosebazooka** [comment] 2019-02-11 19:45
potential CL: #294

**Comment by loosebazooka** [comment] 2019-02-12 20:49
I wonder if this ends up only serving the Java case, and is perhaps a bad way to go about this. Every other language that depends on `zlib1g` also depends on a bunch of other packages. By moving `zlib1g` into `cc`, we've really just made `cc` -> `java-dependencies` without adding any value to `cc` or any of the other images.

Is the actual solution to publish something like `java-base` ?

**Comment by lathama** [comment] 2019-02-12 21:00
would a good example of multistage builds help solve these queries?

**Comment by loosebazooka** [comment] 2019-02-12 21:06
@lathama I think your example is fine, it's an effective strategy for users who have docker. In the jib case, it's less obvious how to do this, I'm just trying to find a good way to go about it.

**Comment by lathama** [comment] 2019-02-12 21:08
Could creating a solution for JIB benefit more long term?

**Comment by loosebazooka** [comment] 2019-02-12 21:10
I think with java11 and tooling around minimizing the JRE, there is a potential for use.

**Comment by dlorenc** [comment] 2019-02-12 21:28
I don't have any preferences.

**Comment by donmccasland** [comment] 2019-11-01 17:34
We now have multistage build examples in the documentation, closing.

**Closed by donmccasland** 2019-11-01 17:34 UTC

**Comment by zifeo** [comment] 2022-07-17 22:23
Note that `lib.so.1` might be symlinked (as of today in `debian:stable-slim`), in case case [lathama](https://github.com/GoogleContainerTools/distroless/issues/217#issuecomment-404551174)'s solution may be extended with `COPY --from=build-env /lib/x86_64-linux-gnu/libz.so* /lib/x86_64-linux-gnu/`.

**Comment by tisonkun** [comment] 2023-01-03 03:06
I encountered this issue and use `ubuntu:jammy` instead https://github.com/korandoru/hawkeye/pull/3.

The problem is that even copy `libz.so`, the `glibc` version required by GraalVM Native Image can be relatively high. In my case, it's >= 2.34 while debian-11 is associated with 2.31.

`ubuntu:jammy` takes 69.2MB while `distroless/base` takes 17.3MB, `debian:bookworm-slim` which has glibc 2.36 takes 96.4MB, and any jre image takes more than 200MB. Finally, I chose `ubuntu:jammy` to avoid issues like this one and has a relatively small size.

**Comment by dlorenc** [comment] 2023-01-03 03:15
> I encountered this issue and use `ubuntu:jammy` instead [korandoru/hawkeye#3](https://github.com/korandoru/hawkeye/pull/3).
> 
> The problem is that even copy `libz.so`, the `glibc` version required by GraalVM Native Image can be relatively high. In my case, it's >= 2.34 while debian-11 is associated with 2.31.
> 
> `ubuntu:jammy` takes 69.2MB while `distroless/base` takes 17.3MB, `debian:bookworm-slim` which has glibc 2.36 takes 96.4MB, and any jre image takes more than 200MB. Finally, I chose `ubuntu:jammy` to avoid issues like this one and has a relatively small size.

Shameless plug - if you get a chance, could you try cgr.dev/chainguard/glibc-dynamic? It's an alternative to distroless/base but with a more modern glibc. I think we use 2.41 now.

**Comment by tisonkun** [comment] 2023-01-03 03:23
@dlorenc do we have a better channel to continue this thread? I'm afraid that it's a bit offensive to discuss here.

Anyway, I try the image and it shows that I should still try to install libz.so myself. Copy binary from another image seems tricky:

```
docker run -it --rm cgr.dev/chainguard/glibc-dynamic ldconfig -p
18 libs found in cache `/etc/ld.so.cache'
	libutil.so.1 (libc6,AArch64) => /lib/libutil.so.1
	libthread_db.so.1 (libc6,AArch64) => /lib/libthread_db.so.1
	librt.so.1 (libc6,AArch64) => /lib/librt.so.1
	libresolv.so.2 (libc6,AArch64) => /lib/libresolv.so.2
	libpthread.so.0 (libc6,AArch64) => /lib/libpthread.so.0
	libnss_files.so.2 (libc6,AArch64) => /lib/libnss_files.so.2
	libnss_dns.so.2 (libc6,AArch64) => /lib/libnss_dns.so.2
	libnss_compat.so.2 (libc6,AArch64) => /lib/libnss_compat.so.2
	libnsl.so.1 (libc6,AArch64) => /lib/libnsl.so.1
	libmemusage.so (libc6,AArch64) => /lib/libmemusage.so
	libm.so.6 (libc6,AArch64) => /lib/libm.so.6
	libdl.so.2 (libc6,AArch64) => /lib/libdl.so.2
	libcrypt.so.1 (libc6,AArch64) => /lib/libcrypt.so.1
	libc_malloc_debug.so.0 (libc6,AArch64) => /lib/libc_malloc_debug.so.0
	libc.so.6 (libc6,AArch64) => /lib/libc.so.6
	libanl.so.1 (libc6,AArch64) => /lib/libanl.so.1
	libBrokenLocale.so.1 (libc6,AArch64) => /lib/libBrokenLocale.so.1
	ld-linux-aarch64.so.1 (libc6,AArch64) => /lib/ld-linux-aarch64.so.1
Cache generated by: ldconfig (GNU libc) stable release version 2.36
```

**Comment by dlorenc** [comment] 2023-01-03 12:57
I opened an issue and cc'ed you there - https://github.com/chainguard-images/images/issues/171

**Comment by dlorenc** [comment] 2023-01-07 18:05
Closing the loop for everyone, there's now a dedicated graal image published here: https://github.com/chainguard-images/images/tree/main/images/graalvm-native-image-base

**Comment by pawelprazak** [comment] 2024-02-03 19:05
Thank you @dlorenc for the link.

FYI: the dir was renamed, new link: https://github.com/chainguard-images/images/tree/main/images/graalvm-native
