### ISSUE TITLE
Use 64bit versions of binaries

### ISSUE THREAD

**Issue by steren** [GoogleContainerTools/distroless#352] opened 2019-05-03 20:03 UTC
gVisor is not able to run 32bit binaries. distroless images are using the 32bit version of busybox, as a consequence, images created with distroless are failing on gVisor.

**Comment by chanseokoh** [comment] 2019-05-06 16:20
Hmm... I get the impression that BusyBox intentionally provides a single pre-compiled binary (for simplicity and manageability for example?) as they say

> The "busybox-i686" version should run on both 32-bit and 64-bit x86 PCs

Technically we may be able to compile a 64-bit binary from source on our own, but I don't know if that is a good idea in terms of reliability and support. Maybe it doesn't matter much as a debug tool.

**Comment by abergmeier** [comment] 2019-05-31 10:41
The problem is not only gVisor. We currently encounter also https://github.com/GoogleContainerTools/distroless/issues/225 on our Kubernetes cluster.
Which makes the debug image to a large degree unusable.
IIUC #225 should be fixed by 64-bit build.

**Comment by chanseokoh** [comment] 2020-05-21 20:14
Fixed by #513.

**Closed by chanseokoh** 2020-05-21 20:14 UTC
Labels: help wanted, kind/enhancement
