### ISSUE TITLE
distroless/java missing libharfbuzz.so.0

### ISSUE THREAD

**Issue by dawwe** [GoogleContainerTools/distroless#729] opened 2021-04-28 10:57 UTC
Description of the issue: The docker images build ok with Jib, but I get an exception thrown when the container runs. The application is a spring boot 2.4.x app that runs ok in the IDE against java 11.

Started with the java:11 image a couple of days ago, older images works. 

Expected behavior: No exception

Steps to reproduce: Jib a spring boot 2.4.x app that uses apache poi and creates Excelfiles. 

Environment: Mac  / Java 11 / Maven / Spring boot

Log output: 

`Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-openjdk-amd64/lib/libfontmanager.so: libharfbuzz.so.0: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at java.desktop/sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:57)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
        at java.desktop/sun.font.SunFontManager$1.run(SunFontManager.java:279)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.SunFontManager.<clinit>(SunFontManager.java:275)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at java.desktop/java.awt.Font.getFont2D(Font.java:497)
        at java.desktop/java.awt.Font.canDisplayUpTo(Font.java:2250)
        at java.desktop/java.awt.font.TextLayout.singleFont(TextLayout.java:469)
        at java.desktop/java.awt.font.TextLayout.<init>(TextLayout.java:530)
        at org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(SheetUtil.java:285)
        at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:117)
        at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:89)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:701)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:722)`

**Comment by dawwe** [comment] 2021-04-28 11:33
tobiaskrauss issue [730](https://github.com/GoogleContainerTools/distroless/issues/730) has better information with test case. 

libharfbuzz0b is a dependency for "openjdk-11-jre-headless (11.0.11+9-1~deb10u1)"

**Comment by scarytom** [comment] 2021-04-28 23:14
I'm experiencing this issue too.

Given this failure has happened twice before (see issue #321 and issue #505), I wonder if we can establish an automated test to prevent it happening again.  I think tobiaskrauss has something pretty minimal in issue #730.  I don't know much about the automated build/deploy pipeline for the distroless images, but I'm happy to try and create a pull request to introduce an automated test if someone gives me a pointer in the right direction.  I had a quick look in the testdata directory, and it appears that we might be able to do something like CheckCerts.java but for fonts?

**Comment by saskodh** [comment] 2021-05-06 14:31
Same issue here, we have to go back to [this build](gcr.io/distroless/java@sha256:1606422cc472612cb5bcd885684b4bf87b3813246c266df473357dce5a0fb4b4) while the issue is resolved. 🙏

**Comment by rdbalderama** [comment] 2021-05-07 12:07
it resulted to page not found @saskodh

**Comment by saskodh** [comment] 2021-05-07 12:35
@rdbalderama, I'm sorry, I just updated the link. 🙏

**Comment by rdbalderama** [comment] 2021-05-07 12:51
omg, you're an angel, I'm going crazy because of this issue. thanks @saskodh

**Comment by scarytom** [comment] 2021-05-10 20:16
Has anyone attempted to track down whether a specific commit caused this issue yet?  I was having a quick poke, and potentially this one: https://github.com/GoogleContainerTools/distroless/pull/712/commits/822f68f39c5bf1b91cebb09e0c41016f85b2d9da on pull request #712 as part of issue #709.  Not sure though.

**Comment by scarytom** [comment] 2021-05-11 11:39
Thanks @tobiaskrauss -- in hindsight this was evident from your comment on issue #730 https://github.com/GoogleContainerTools/distroless/issues/730#issuecomment-828533027

**Comment by mat-613** [comment] 2021-07-08 15:41
I have the same issue, what about the solution?

**Comment by MrBuddyCasino** [comment] 2021-07-28 13:10
Same, just hit this while using the latest java11 image. 
Would a PR with a failing test help?

**Comment by shay-berman** [comment] 2021-08-29 13:30
@MrBuddyCasino can you mention what is the full path of the image please?

**Comment by MrBuddyCasino** [comment] 2021-08-30 10:09
@shay-berman I'm using `distroless/java@sha256:1606422cc472612cb5bcd885684b4bf87b3813246c266df473357dce5a0fb4b4`

**Comment by MrBuddyCasino** [comment] 2021-08-30 11:39
I couldn't figure out in a hurry how to make a proper test case, but this code is sufficient to trigger the exception, using `org.apache.poi:poi-ooxml:4.1.2` as dependency:
```
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class Application {
    public static void main(String[] args) {
        createWorkbook();
    }

    static void createWorkbook() {
        var wb = new XSSFWorkbook();
        var sheet = wb.createSheet("Test");
        var header = sheet.createRow(0);
        header.createCell(0);
        sheet.autoSizeColumn(0);
    }
}
```
Results in: `Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-openjdk-amd64/lib/libfontmanager.so: libharfbuzz.so.0: cannot open shared object file: No such file or directory` when using the `gcr.io/distroless/java:11` image.

**Comment by MrBuddyCasino** [comment] 2021-08-30 12:37
And here a version without dependencies:
```
import java.awt.font.FontRenderContext;
import java.awt.font.TextLayout;
import java.text.AttributedString;

public class Application {
    public static void main(String[] args) {
        FontRenderContext ctx = new FontRenderContext(null, true, true);
        AttributedString str = new AttributedString("test");
        new TextLayout(str.getIterator(), ctx);
    }
}
```

**Comment by Jayaprabahar** [comment] 2021-09-03 07:51
I moved to "docker pull openjdk:11-jre-buster"

**Comment by shay-berman** [comment] 2021-09-12 14:20
@MrBuddyCasino thanks for mentioning the full path of the image that is working.
BUT what if I am running it with maven jib and the WAR is using Jetty image and not just Java?

What jetty image support this?

**Comment by loosebazooka** [comment] 2021-09-13 13:13
should be fixed in the next build.

**Comment by tobiaskrauss** [comment] 2021-09-23 12:57
Tested successfully with latest released java:11-nonroot image (sha256:deb41661be772c6256194eb1df6b526cc95a6f60e5f5b740dda2769b20778c51).
From my point of view the issue is resolved.

**Comment by nmaoez** [comment] 2021-09-27 09:24
My tests were also successful with the image [gcr.io/distroless/java-debian10:11-debug](https://console.cloud.google.com/gcr/images/distroless/global/java-debian10@sha256:0551431d74d180cb50e5354732388aff55e896691ad79f20da4897fecee1feed/details), so therefore this issue is resolved. Thanks!!!!

**Closed** 2021-09-27 13:43 UTC

**Comment by shay-berman** [comment] 2021-10-06 06:58
thanks a lot, the fix works
