### ISSUE TITLE
Should the Java 11 version have ca certs out of the box?

### ISSUE THREAD

**Issue by mattjs** [GoogleContainerTools/distroless#425] opened 2019-10-28 19:32 UTC
Im trying to connect to a site over HTTPS inside a Java 11 image and I am getting SSL errors like below

```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

It seems like the ca certs should be included from a bit of digging through the code.

My `WORKSPACE` looks like this

```
container_pull(
  name = "java_11_base",
  registry = "gcr.io",
  repository = "distroless/java",
  digest = "sha256:f9fe0de7f8ded68f757d99e9d165b96e89e00d4cef80d204aa76bc0b8ffc4576",
)
```

Any idea what could be going wrong here? Thanks!

**Comment by chanseokoh** [comment] 2019-10-28 19:50
Works for me. Which URL are you trying?

- `Dockerfile`
```Dockerfile
FROM gcr.io/distroless/java@sha256:f9fe0de7f8ded68f757d99e9d165b96e89e00d4cef80d204aa76bc0b8ffc4576
ADD A.java /
ENTRYPOINT ["java", "/A.java"]
```
- `A.java`
```java
import java.io.IOException;
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;

public class A {

  public static void main(String[] args) throws IOException {
    URL url = new URL("https://www.google.com/");
    HttpsURLConnection conn = (HttpsURLConnection) url.openConnection();
    conn.connect();
    conn.getServerCertificates(); // succeeds if peer verified

    System.out.println("Successfully connected: " + conn.getResponseCode());
  }
}
```

```
$ docker build -t test .
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM gcr.io/distroless/java@sha256:f9fe0de7f8ded68f757d99e9d165b96e89e00d4cef80d204aa76bc0b8ffc4576
 ---> 7020ecd1c68b
Step 2/3 : ADD A.java /
 ---> 57759461810a
Step 3/3 : ENTRYPOINT ["java", "/A.java"]
 ---> Running in 757c17cf8345
Removing intermediate container 757c17cf8345
 ---> a8e8edb13fb7
Successfully built a8e8edb13fb7
Successfully tagged test:latest

$ docker run --rm test
Successfully connected: 200
```

Can you come up with a simple `Dockerfile` that reproduces this issue?

**Comment by mattjs** [comment] 2019-10-28 20:13
Seems like it might just be the site actually, my personal site `https://brownbear.tech` I just tested https://www.google.com/ with my code and it is working fine.

Hoping now I have my certificates set up properly but the site seems to verify properly on Chrome.

**Comment by chanseokoh** [comment] 2019-10-28 20:16
Yeah, https://brownbear.tech doesn't even work on my local machine (i.e., no Docker involved) on Java (tested with Java 8). This seems nothing to do with Distroless.

**Comment by chanseokoh** [comment] 2019-10-28 20:31
I'll close this, since apparently this has nothing to do with Distroless. But I am personally curious what the cause and how this will be resolved, so I'd appreciate your update later.

**Closed by chanseokoh** 2019-10-28 20:31 UTC
